### ISSUE TITLE
Problem with encoding

### ISSUE THREAD

**Issue by Sitmobedaf** [Aztorius/craftconomy3#11]
I have probles with encoding in database. I wand put currency "монет", but i recieved "?????".
It is latin1, you can set charset to utf8?

**Comment by Aztorius** [comment]
I will look for that issue.
I think it may be latin1.
Do you use an SQL database or the H2 database (default) ?

**Comment by Sitmobedaf** [comment]
I use MySQL. Russian text may not be in latin1, as well as many others.

**Comment by Aztorius** [comment]
This is an alpha update, it may solve your issue but you need a new database to test it.
(unzip it and try to use the .jar)
[craftconomy3-3.4.0-test.zip](https://github.com/Aztorius/craftconomy3/files/873537/craftconomy3-3.4.0-test.zip)

**Comment by Sitmobedaf** [comment]
It is working! Thanks!
