### ISSUE TITLE
Sponge: Plugin ID should be all lowercase

### ISSUE THREAD

**Issue by Stuperfied** [Aztorius/craftconomy3#12]
Firstly, thank you for taking up the project. 

The original version of this plugin is reported to have sponge compatibility. I have also reported this issue in the original project.

[12:19:34 INFO]: SpongeVanilla
    Minecraft: 1.11.2
    SpongeAPI: 6.0.0-SNAPSHOT-1822f21
    SpongeVanilla: 1.11.2-6.0.0-BETA-220

[12:16:50 ERROR] [Sponge]: Skipping plugin with invalid plugin ID 'GreatmancodeToolsLoader' from mods\craftconomy3-master-3.4.0-SNAPSHOT.jar. Plugin IDs should be lowercase, and only contain characters from a-z, dashes or underscores, start with a lowercase letter, and not exceed 64 characters.

**Comment by Aztorius** [comment]
I think I cannot change the plugin ID "GreatmancodeToolsLoader" easly.
I will look for that.
But maybe you can try with an older version of Sponge ?

**Comment by Stuperfied** [comment]
I'm not too worried as we are only trialing sponge at this point in time. I am glad you picked up this project, its a good one I used to use on spigot for its multi world support.

I spent a while trying to find where the ID is before I posted but couldn't find it. If you can track it down, could you let me know where it was? Just for curiosity sake.

**Comment by Aztorius** [comment]
Found in a dependency called Greatmancode Tools.
https://github.com/greatman/GreatmancodeTools/blob/75d4fa391aadef95d6d5c1fd773429f4fba2d169/src/main/java/com/greatmancode/tools/interfaces/SpongeLoader.java#L40
I need to fork this project, to change this line and to compile craftconomy with the new version.

**Comment by Aztorius** [comment]
Ok, the fix now works. But there are other issues.
I will keep a Sponge test server to fix the plugin.
[craftconomy3-3.4.0-test.zip](https://github.com/Aztorius/craftconomy3/files/878140/craftconomy3-3.4.0-test.zip)

**Comment by Stuperfied** [comment]
Sorry for the late reply. Thanks, i'll test it today as soon as I have access to the server.
