### ISSUE TITLE
Currency color format 

### ISSUE THREAD

**Issue by madtomic** [Aztorius/craftconomy3#14]
Add currency color format support for price:
10 Gold 00 Silver

Major: gold color or &6
Minor: silver color or &7

Then, no need for a comma when using colors

**Comment by madtomic** [comment]
Really look forward to this feature to be added.

**Comment by Aztorius** [comment]
Done. Use this test build and try it.
[craftconomy3-3.4.0-test.zip](https://github.com/Aztorius/craftconomy3/files/888234/craftconomy3-3.4.0-test.zip)

**Comment by madtomic** [comment]
Thank you for adding this but a slight tweak if you would.

![image](https://cloud.githubusercontent.com/assets/6004542/24594048/1171f666-17f7-11e7-9b2d-a0ebca7fb2b2.png)

Can you also make the currency name - Gold same color as CurrencyMajorColor and Silver same color as CurrencyMinorColor

Thanks again!

**Comment by Aztorius** [comment]
Ok. Now I think it's good.
[craftconomy3-3.4.0-test.zip](https://github.com/Aztorius/craftconomy3/files/891188/craftconomy3-3.4.0-test.zip)

**Comment by madtomic** [comment]
Can you please help me with loading error? Thanks!

https://pastebin.com/fVEZftTM

**Comment by Aztorius** [comment]
Sorry, it was a change in GreatmancodeTools : https://github.com/Aztorius/GreatmancodeTools
I will fix it.

**Comment by Aztorius** [comment]
Finally.
[craftconomy3-3.4.0-test.zip](https://github.com/Aztorius/craftconomy3/files/893432/craftconomy3-3.4.0-test.zip)

**Comment by Aztorius** [comment]
Finally.
[craftconomy3-3.4.0-test.zip](https://github.com/Aztorius/craftconomy3/files/893457/craftconomy3-3.4.0-test.zip)

**Comment by madtomic** [comment]
So far so good. Thank you very much again!
