### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by Stuperfied** [Aztorius/craftconomy3#18]
Craftconomy3 displays permission denied when using /money balance
https://cdn.discordapp.com/attachments/304039536772775936/323646691767091200/Screen_Shot_2017-06-11_at_7.16.16_PM.png

user has all of the following permissions except for the ones labeled for admins
https://github.com/greatman/craftconomy3/wiki/Permissions

[permissions.zip](https://github.com/Aztorius/craftconomy3/files/1066965/permissions.zip)

This is on a Windows 7 spigot server.
User is on 1.11.2 client
craftconomy3-3.4.0-SNAPSHOT.jar

**Comment by Aztorius** [comment]
These permissions are working for me. Try it in these order.
```
    - craftconomy.money.balance
    - craftconomy.money.pay
    - craftconomy.money.top
    - craftconomy.bank.create
    - craftconomy.bank.balance
    - craftconomy.bank.deposit
    - craftconomy.bank.perm
    - craftconomy.bank.withdraw
    - craftconomy.bank.list
```

**Comment by Stuperfied** [comment]
I put in those permissions exactly as you have there but the player still cant do /money balance

**Comment by Stuperfied** [comment]
Also, Player is able to use the LobbyCompass plugin in that server which suggests that pex is not the issue.

**Comment by Aztorius** [comment]
The real command is only `/money`. When you type `/money balance` he try to retrieve the amount in an account called balance which doesn't exist. Try it with only `/money`, it should works.

**Comment by Aztorius** [comment]
Can you confirm it works ?
I closed it for now.

**Comment by Stuperfied** [comment]
It works thanks...
