### ISSUE TITLE
Error when i compile the plugin

### ISSUE THREAD

**Issue by Sitmobedaf** [Aztorius/craftconomy3#19]
Error:
https://pastebin.com/MeL5vs4J

I checked it with Windows 10 and Ubuntu 16.04

**Comment by Aztorius** [comment]
It's an error when signing the archive, it's also in the original repository.
You can ignore it. JAR files are in build/libs

**Comment by Sitmobedaf** [comment]
There are no files there.

**Comment by Aztorius** [comment]
Check with the last commit.

**Comment by Sitmobedaf** [comment]
https://www.youtube.com/watch?v=IntjGoN4lfc&feature=youtu.be

**Comment by Aztorius** [comment]
I changed this a while ago. I will try to revert that because currently it needs my custom GreatmanCodeTools.

**Comment by Sitmobedaf** [comment]
How do you compile the plugin? How do I compile the plugin?

**Comment by Aztorius** [comment]
I will commit, it will work just fine. You can also simply download the jar file if you only need this.
